services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: eve_diagnostics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eve_diagnostics"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://db:5432/eve_diagnostics
      DB_USERNAME: postgres
      DB_PASSWORD: 12345678
      APP_JWT_SECRET: ${APP_JWT_SECRET:xRq2cV6a9ig5KRk151YAKjeroR9LJeksu0Y5OUztOgS}
      APP_WEBHOOK_SECRET: ${APP_WEBHOOK_SECRET:dddaa3bb41dd5909aa27b3ee9cca528b1b016998835a66b549726e966e7e89bd}

volumes:
  pgdata:
