CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE diagnostic_tests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL
);
CREATE UNIQUE INDEX uq_diagnostic_tests_name ON diagnostic_tests (lower(name));

CREATE TABLE diagnostic_centres (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(150) NOT NULL,
    location   VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL
);
CREATE UNIQUE INDEX uq_diagnostic_centres_name_location ON diagnostic_centres (lower(name), lower(location));
CREATE INDEX idx_diagnostic_centres_location ON diagnostic_centres (lower(location));

-- Which test a centre offers, and at what price (price is per centre).
CREATE TABLE centre_tests (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centre_id BIGINT         NOT NULL REFERENCES diagnostic_centres (id) ON DELETE CASCADE,
    test_id   BIGINT         NOT NULL REFERENCES diagnostic_tests (id),
    price     NUMERIC(12, 2) NOT NULL,
    CONSTRAINT uq_centre_tests UNIQUE (centre_id, test_id),
    CONSTRAINT chk_centre_tests_price CHECK (price > 0)
);
CREATE INDEX idx_centre_tests_test ON centre_tests (test_id);

CREATE TABLE bookings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT         NOT NULL REFERENCES users (id),
    centre_id        BIGINT         NOT NULL REFERENCES diagnostic_centres (id),
    test_id          BIGINT         NOT NULL REFERENCES diagnostic_tests (id),
    appointment_time TIMESTAMPTZ    NOT NULL,
    amount           NUMERIC(12, 2) NOT NULL,   -- price snapshot taken at booking time
    status           VARCHAR(20)    NOT NULL,
    version          BIGINT         NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ    NOT NULL,
    updated_at       TIMESTAMPTZ    NOT NULL,
    CONSTRAINT chk_bookings_status CHECK (status IN ('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED')),
    CONSTRAINT chk_bookings_amount CHECK (amount > 0)
);
CREATE INDEX idx_bookings_user_created ON bookings (user_id, created_at DESC);
CREATE INDEX idx_bookings_user_status ON bookings (user_id, status);

CREATE TABLE payments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id         BIGINT         NOT NULL REFERENCES bookings (id),
    amount             NUMERIC(12, 2) NOT NULL,
    status             VARCHAR(20)    NOT NULL,
    provider_reference VARCHAR(64)    NOT NULL,
    idempotency_key    VARCHAR(100),
    failure_reason     VARCHAR(255),
    created_at         TIMESTAMPTZ    NOT NULL,
    updated_at         TIMESTAMPTZ    NOT NULL,
    CONSTRAINT uq_payments_provider_reference UNIQUE (provider_reference),
    CONSTRAINT uq_payments_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT chk_payments_status CHECK (status IN ('SUCCESS', 'FAILED'))
);
CREATE INDEX idx_payments_booking ON payments (booking_id);
-- Last line of defence against double charging: at most one SUCCESS payment per booking.
CREATE UNIQUE INDEX uq_payments_one_success_per_booking ON payments (booking_id) WHERE status = 'SUCCESS';

-- Every webhook event we have accepted. The UNIQUE(event_id) is what makes the webhook idempotent.
CREATE TABLE webhook_events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          VARCHAR(100) NOT NULL,
    payment_reference VARCHAR(64)  NOT NULL,
    event_status      VARCHAR(20)  NOT NULL,
    outcome           VARCHAR(30)  NOT NULL,
    payload           TEXT,
    received_at       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_webhook_events_event_id UNIQUE (event_id)
);
